### ISSUE TITLE
Is it possible to have a tagged release?

### ISSUE THREAD

**Issue by vincentlepot** [tawfekov/ar-php#13]
Hi,

Is it possible to add a tagged release? This would avoid a warning in composer saying it's not a good practice to depend on `dev-master`.

**Comment by devlor** [comment]
Hi @vincentlepot , 

sorry for the delay , sure , I'll create a tag now

**Comment by tawfekov** [comment]
Hi @vincentlepot ,

sorry for the delay , sure , here is a tag : https://packagist.org/packages/ar-php/ar-php#v1.0

**Comment by vincentlepot** [comment]
Thanks 🙏
