### ISSUE TITLE
No readme?

### ISSUE THREAD

**Issue by krewetka** [tawfekov/ar-php#16]
Hi!

Why readme is just saying it is fork of...the same repository? 

Is there anywhere readme for original library?

**Comment by tawfekov** [comment]
Hi @krewetka 

by that time the original author @khaled.alshamaa didn't have a github / packagist support (as far as I knew) so I created it to use it in my own projects 

you reminded me now to check again and I've found that he created his own packagist repo : https://github.com/khaled-alshamaa/ar-php , https://packagist.org/packages/khaled.alshamaa/ar-php 

you are welcome to use the original library now

**Comment by tawfekov** [comment]
I've just abandoned it on packgist too in favor of the original one

**Comment by krewetka** [comment]
Ok, I have found it as well after doing some more searching.
