### ISSUE TITLE
for some reason I cannot get it via composer

### ISSUE THREAD

**Issue by alexseif** [tawfekov/ar-php#9]
I run
`$ composer require ar-php/ar-php`
and I get
`Could not find package ar-php/ar-php at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`

**Comment by tawfekov** [comment]
will you please try now and let me know if this issue persisted

**Comment by alexseif** [comment]
Thank you, i can't right now, but I'll pick this up tomorrow.

**Comment by alexseif** [comment]
Thank you, i can't right now, but I'll pick this up tomorrow.
On Jun 10, 2016 8:08 PM, "Tawfek Daghistani" notifications@github.com
wrote:

will you please try now and let me know if this issue persisted

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/tawfekov/ar-php/issues/9#issuecomment-225254690, or mute
the thread
https://github.com/notifications/unsubscribe/AA1-4Dvy4PiK_qPbG5Dk-9kQgAKQ0smHks5qKagdgaJpZM4IzHLR
.

**Comment by alexseif** [comment]
Yes the issue still persists.

```
composer require ar-php/ar-php


  [InvalidArgumentException]                                                                                                                     
  Could not find package ar-php/ar-php at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  

```

**Comment by peter-mw** [comment]
hi

this is how i made it work

in composer.json

```

{
  "require": {
   //... your stuff
  },
  "require-dev": {
    "ar-php/ar-php": "dev-master"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/tawfekov/ar-php.git"
    }
  ],
  "minimum-stability": "dev"
}
```
